"""Add read_more_link to NewsArticle table

Revision ID: 1e9aaed8b50b
Revises: d01c7cba2f74
Create Date: 2025-06-27 12:07:53.569655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9aaed8b50b'
down_revision = 'd01c7cba2f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_more_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.drop_column('read_more_link')

    # ### end Alembic commands ###
